@extends('layouts.app')

@section('content')
@php
  $productImages = collect([$product->image_path])->merge($product->gallery ?? [])->filter()->unique()->values();
@endphp
<section class="section product-detail-section"><div class="container product-detail-grid"><div class="product-gallery">@foreach($productImages as $image)<img src="{{ str_starts_with($image, '/') ? $image : \Illuminate\Support\Facades\Storage::url($image) }}" alt="{{ $product->name }}" class="gallery-thumb" loading="lazy" />@endforeach</div><div class="product-info"><span class="eyebrow">{{ $product->category?->name }}</span><h1>{{ $product->name }}</h1><p class="product-price">Product enquiry</p><p>{{ $product->description }}</p><a class="btn primary" href="/contact?product={{ urlencode($product->name) }}">Enquire now</a><div class="meta-row"><span>Pack: {{ $product->pack }}</span><span>Stock: {{ $product->stock }}</span></div><div class="product-detail-copy"><h3>Specifications</h3><ul class="spec-list">@foreach($product->specs ?? [] as $spec)<li>{{ $spec }}</li>@endforeach</ul><h3>Usage</h3><p>{{ $product->usage }}</p></div></div></div></section>
@if($related->isNotEmpty())<section class="section"><div class="container"><div class="section-heading"><span class="eyebrow">Related products</span><h2>You may also like</h2></div><div class="product-grid compact-grid">@foreach($related as $item)<article class="product-card"><div class="product-image-wrap"><a href="/shop/{{ $item->slug }}"><img src="{{ str_starts_with($item->image_path ?? '', '/') ? $item->image_path : \Illuminate\Support\Facades\Storage::url($item->image_path ?? '') }}" alt="{{ $item->name }}" loading="lazy" /></a></div><div class="card-copy"><h3><a href="/shop/{{ $item->slug }}">{{ $item->name }}</a></h3><p>{{ $item->pack }}</p><a class="btn enquiry-button" href="/contact?product={{ urlencode($item->name) }}">Enquire now</a></div></article>@endforeach</div></div></section>@endif
@endsection
