@extends('layouts.app')
@section('content')
<section class="page-hero compact"><div class="container"><span class="eyebrow">Ricevibe admin</span><h1>Store management</h1><form method="post" action="{{ route('admin.logout') }}">@csrf<button class="btn secondary" type="submit">Sign out</button></form></div></section>
<section class="section"><div class="container admin-shell">@if(session('status'))<p class="form-status">{{ session('status') }}</p>@endif
<h2>Products</h2><form class="admin-item-form" method="post" action="{{ route('admin.products.store') }}" enctype="multipart/form-data">@csrf<h3>Add product</h3><label>Name<input name="name" required /></label><label>Slug<input name="slug" /></label><label>Category<select name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label><label>Pack / size<input name="pack" /></label><label>Price<input name="price" type="number" min="0" /></label><label>Image<input name="image_file" type="file" accept="image/*" /></label><label class="admin-editor-wide">Description<textarea name="description"></textarea></label><label>Usage<textarea name="usage"></textarea></label><label>Stock<input name="stock" /></label><button class="btn primary" type="submit">Add product</button></form>
@foreach($products as $product)<details class="admin-section"><summary>{{ $product->name }} <small>{{ $product->category?->name }}</small></summary><form class="admin-item-form" method="post" action="{{ route('admin.products.update', $product) }}" enctype="multipart/form-data">@csrf @method('PUT')<label>Name<input name="name" value="{{ $product->name }}" required /></label><label>Slug<input name="slug" value="{{ $product->slug }}" /></label><label>Category<select name="category_id">@foreach($categories as $category)<option value="{{ $category->id }}" @selected($category->id === $product->category_id)>{{ $category->name }}</option>@endforeach</select></label><label>Pack<input name="pack" value="{{ $product->pack }}" /></label><label>Price<input name="price" type="number" min="0" value="{{ $product->price }}" /></label><label>Replace image<input name="image_file" type="file" accept="image/*" /></label><label class="admin-editor-wide">Description<textarea name="description">{{ $product->description }}</textarea></label><label>Usage<textarea name="usage">{{ $product->usage }}</textarea></label><label>Stock<input name="stock" value="{{ $product->stock }}" /></label><button class="btn primary" type="submit">Save product</button></form><form method="post" action="{{ route('admin.products.destroy', $product) }}">@csrf @method('DELETE')<button class="text-button" type="submit">Delete product</button></form></details>@endforeach
<h2>Banners</h2><form class="admin-item-form" method="post" action="{{ route('admin.banners.store') }}" enctype="multipart/form-data">@csrf<h3>Add banner</h3><label>Title<input name="title" required /></label><label>Subtitle<input name="subtitle" /></label><label>Image<input name="image_file" type="file" accept="image/*" required /></label><label>Button text<input name="button_text" /></label><label>Button link<input name="button_link" value="/shop" /></label><button class="btn primary" type="submit">Add banner</button></form>
@foreach($banners as $banner)<details class="admin-section"><summary>{{ $banner->title }}</summary><form class="admin-item-form" method="post" action="{{ route('admin.banners.update', $banner) }}" enctype="multipart/form-data">@csrf @method('PUT')<label>Title<input name="title" value="{{ $banner->title }}" required /></label><label>Subtitle<input name="subtitle" value="{{ $banner->subtitle }}" /></label><label>Replace image<input name="image_file" type="file" accept="image/*" /></label><label>Button text<input name="button_text" value="{{ $banner->button_text }}" /></label><label>Button link<input name="button_link" value="{{ $banner->button_link }}" /></label><button class="btn primary" type="submit">Save banner</button></form><form method="post" action="{{ route('admin.banners.destroy', $banner) }}">@csrf @method('DELETE')<button class="text-button" type="submit">Delete banner</button></form></details>@endforeach
<h2>Site content</h2>@foreach($contents as $content)<details class="admin-section"><summary>{{ str_replace('_', ' ', ucfirst($content->section)) }}</summary><form method="post" action="{{ route('admin.content.update', $content->section) }}">@csrf @method('PUT')<label>JSON content<textarea class="admin-editor-wide" name="payload" rows="12">{{ json_encode($content->payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</textarea></label><button class="btn primary" type="submit">Save content</button>@error('payload')<p class="form-status">{{ $message }}</p>@enderror</form></details>@endforeach
<h2>Recent enquiries</h2><div class="admin-table-wrap"><table class="admin-product-table"><thead><tr><th>Name</th><th>Contact</th><th>Type</th><th>Product</th><th>Message</th><th>Date</th></tr></thead><tbody>@forelse($enquiries as $enquiry)<tr><td>{{ $enquiry->name }}<small>{{ $enquiry->company }}</small></td><td>{{ $enquiry->email }}<small>{{ $enquiry->phone }}</small></td><td>{{ $enquiry->enquiry_type }}</td><td>{{ $enquiry->product }}</td><td>{{ $enquiry->message }}</td><td>{{ $enquiry->created_at->format('Y-m-d') }}</td></tr>@empty<tr><td colspan="6">No enquiries yet.</td></tr>@endforelse</tbody></table></div>
</div></section>
@endsection