SITE_DATA = {
    "brand": {
        "name": "Ricevibe",
        "tagline": "Biodegradable rice straws and eco-friendly essentials by JP Enterprises.",
        "location": "Bajanai Koil St, Ishwarya Nagar, Naduvankarai, Anna Nagar, Chennai, Tamil Nadu 600040",
        "phone": "093423 28664",
        "email": "hello@ricevibe.in",
        "whatsapp": "https://wa.me/919342328664",
        "address": "Bajanai Koil St, Ishwarya Nagar, Naduvankarai, Anna Nagar, Chennai, Tamil Nadu 600040",
        "logo_name": "ricevibe",
        "logo_alt": "Ricevibe logo",
    },
    "nav": [
        {"label": "Home", "url": "/"},
        {"label": "Shop", "url": "/shop"},
        {"label": "About Us", "url": "/about-us"},
        {"label": "Gallery", "url": "/gallery"},
        {"label": "Brochure", "url": "/brochure"},
        {"label": "FAQ", "url": "/faq"},
        {"label": "Enquire", "url": "/contact"},
    ],
    "hero": [],
    "homepage": {
        "categories_heading": "Eco-friendly essentials for every sip",
        "products_heading": "Popular products",
        "why_heading": "Purpose-built for sustainable hospitality",
        "sustainability_heading": "Made from Nature. Made for a Better Tomorrow.",
        "bulk_heading": "Better Choices for Your Business",
        "feedback_heading": "Good straws. Happier service.",
    },
    "categories": [
        {
            "slug": "rice-straws",
            "name": "Rice Straws",
            "image": "/static/assets/ricevibe/rice-straw-main.jpg",
            "description": "Food-grade rice straws for juices, smoothies, mocktails and cocktails.",
        },
        {
            "slug": "wooden-stirrers",
            "name": "Wooden Stirrers",
            "image": "/static/assets/ricevibe/rice-straw-gallery-3.jpg",
            "description": "Natural stirrers for coffee, tea and signature drinks.",
        },
        {
            "slug": "garnish-sticks",
            "name": "Garnish Sticks",
            "image": "/static/assets/ricevibe/garnish-1.jpg",
            "description": "Elegant garnish tools for premium beverage presentation and hospitality service.",
        },
    ],
    "why_ricevibe": [
        {"title": "Biodegradable", "text": "Designed to disappear naturally after use without leaving plastic behind.", "icon": "leaf"},
        {"title": "Food-safe", "text": "Produced for food and beverage use with the right handling and packaging standards.", "icon": "shield"},
        {"title": "Eco-friendly", "text": "Made for conscious hospitality and retail businesses reducing plastic dependency.", "icon": "spark"},
        {"title": "Natural", "text": "Clean, earthy and premium look that aligns with natural ingredient experiences.", "icon": "sun"},
        {"title": "Hospitality ready", "text": "Built for cafés, restaurants, bars, and event service setups requiring consistency.", "icon": "cup"},
        {"title": "Bulk supply", "text": "Reliable formats for hotels, restaurants, caterers, retailers and distributors.", "icon": "box"},
        {"title": "Plant-based", "text": "Made with plant-derived ingredients for a more natural everyday alternative.", "icon": "leaf"},
        {"title": "Plastic-free choice", "text": "A practical way to reduce dependence on conventional single-use plastic straws.", "icon": "spark"},
        {"title": "Earth-conscious", "text": "A thoughtful product choice for teams working toward cleaner, lower-impact service.", "icon": "sun"},
        {"title": "Naturally stylish", "text": "Warm natural textures and a premium finish that complement modern beverage presentation.", "icon": "cup"},
    ],
    "products": [
        {
            "id": 1,
            "name": "Rice Straws - 8mm Natural",
            "slug": "rice-straws-8mm-natural",
            "category": "Rice Straws",
            "category_slug": "rice-straws",
            "pack": "500 pcs / pack",
            "price": 390,
            "image": "/static/assets/ricevibe/rice-straw-main.jpg",
            "gallery": [
                "/static/assets/ricevibe/rice-straw-main.jpg",
                "/static/assets/ricevibe/rice-straw-gallery-1.jpg",
                "/static/assets/ricevibe/rice-straw-gallery-2.jpg",
            ],
            "description": "A clean, natural sipping solution for juices, shakes, cocktails and mocktails, crafted to complement premium beverage service.",
            "specs": [
                "Material: rice flour and tapioca starch",
                "Length: 20 cm",
                "Diameter: 8 mm",
                "Usage: cold beverages and signature drinks",
            ],
            "usage": "Perfect for cafés, juice bars, restaurants and retail kits. Best for chilled beverages and smooth pours.",
            "stock": "In stock",
            "badge": "Bestseller",
        },
        {
            "id": 2,
            "name": "Rice Straws - 12mm Premium",
            "slug": "rice-straws-12mm-premium",
            "category": "Rice Straws",
            "category_slug": "rice-straws",
            "pack": "500 pcs / pack",
            "price": 450,
            "image": "/static/assets/product-rice-red.jpg",
            "gallery": [
                "/static/assets/product-rice-red.jpg",
                "/static/assets/product-rice-natural.jpg",
                "/static/assets/product-rice-box.jpg",
            ],
            "description": "A larger diameter option for thicker beverages and premium hospitality settings, with a natural finish and smooth sip experience.",
            "specs": [
                "Material: rice flour and tapioca starch",
                "Length: 21 cm",
                "Diameter: 12 mm",
                "Usage: smoothies, iced coffee, milkshakes",
            ],
            "usage": "Ideal for premium cafés, cocktail lounges and curated beverage counters that want a sturdy, eco-conscious straw.",
            "stock": "Ready to ship",
            "badge": "Popular",
        },
        {
            "id": 3,
            "name": "Ricevibe Everyday Pack",
            "slug": "ricevibe-everyday-pack",
            "category": "Wooden Stirrers",
            "category_slug": "wooden-stirrers",
            "pack": "250 pcs / pack",
            "price": 320,
            "image": "/static/assets/product-rice-set.jpg",
            "gallery": [
                "/static/assets/product-rice-set.jpg",
                "/static/assets/product-rice-pack.jpg",
                "/static/assets/product-rice-box.jpg",
            ],
            "description": "A compact Ricevibe pack for daily home use, café counters and takeaway beverage service.",
            "specs": [
                "Material: rice flour and tapioca starch",
                "Pack size: 250 pieces",
                "Finish: natural and food-safe",
                "Usage: everyday cold beverages",
            ],
            "usage": "Great for homes, cafés, quick-service counters and premium takeaway beverage stations.",
            "stock": "In stock",
            "badge": "Everyday pick",
        },
        {
            "id": 4,
            "name": "Rice Straw Box Pack",
            "slug": "rice-straw-box-pack",
            "category": "Wooden Stirrers",
            "category_slug": "wooden-stirrers",
            "pack": "500 pcs / pack",
            "price": 420,
            "image": "/static/assets/product-rice-box.jpg",
            "gallery": [
                "/static/assets/product-rice-box.jpg",
                "/static/assets/product-rice-closeup.jpg",
                "/static/assets/product-rice-red.jpg",
            ],
            "description": "A presentation-ready box pack that keeps natural rice straws organised for service and retail display.",
            "specs": [
                "Material: rice flour and tapioca starch",
                "Pack size: 500 pieces",
                "Packaging: retail-ready box",
                "Usage: cafés, restaurants and retail",
            ],
            "usage": "An easy, premium option for busy service teams that need reliable and natural beverage accessories.",
            "stock": "In stock",
            "badge": "Retail ready",
        },
        {
            "id": 5,
            "name": "Hospitality Rice Straw Bundle",
            "slug": "hospitality-rice-straw-bundle",
            "category": "Garnish Sticks",
            "category_slug": "garnish-sticks",
            "pack": "1000 pcs / bundle",
            "price": 760,
            "image": "/static/assets/product-rice-bundle.jpg",
            "gallery": [
                "/static/assets/product-rice-bundle.jpg",
                "/static/assets/product-rice-box.jpg",
                "/static/assets/product-rice-natural.jpg",
            ],
            "description": "A larger bundle for hotels, restaurant groups, caterers and recurring beverage programmes.",
            "specs": [
                "Material: rice flour and tapioca starch",
                "Pack size: 1000 pieces",
                "Format: hospitality bundle",
                "Usage: recurring beverage service",
            ],
            "usage": "Recommended for hotels, restaurants, caterers and events running recurring beverage programmes.",
            "stock": "Bulk available",
            "badge": "B2B favourite",
        },
        {
            "id": 6,
            "name": "Natural Rice Straw Starter Set",
            "slug": "natural-rice-straw-starter-set",
            "category": "Garnish Sticks",
            "category_slug": "garnish-sticks",
            "pack": "500 pcs / set",
            "price": 540,
            "image": "/static/assets/product-rice-closeup.jpg",
            "gallery": [
                "/static/assets/product-rice-closeup.jpg",
                "/static/assets/product-rice-set.jpg",
                "/static/assets/product-rice-pack.jpg",
            ],
            "description": "A flexible starter set for businesses testing a plastic-free beverage service programme.",
            "specs": [
                "Material: rice flour and tapioca starch",
                "Pack size: 500 pieces",
                "Finish: natural and smooth",
                "Usage: beverage service and events",
            ],
            "usage": "A practical first step for cafés, event planners and hospitality teams moving away from plastic.",
            "stock": "Ready to ship",
            "badge": "Starter set",
        },
    ],
    "gallery": [
        {"title": "Rice straw product range", "category": "Ricevibe Products", "image": "/static/assets/ricevibe/rice-straw-gallery-1.jpg"},
        {"title": "Rice straw packaging", "category": "Ricevibe Products", "image": "/static/assets/ricevibe/rice-straw-gallery-2.jpg"},
        {"title": "Natural 8mm rice straws", "category": "Rice Straw 8mm", "image": "/static/assets/ricevibe/rice-straw-gallery-3.jpg"},
        {"title": "Rice straw close-up", "category": "Rice Straw 8mm", "image": "/static/assets/ricevibe/rice-straw-gallery-4.jpg"},
        {"title": "Garnish sticks", "category": "Garnish Sticks", "image": "/static/assets/ricevibe/garnish-1.jpg"},
        {"title": "Hospitality garnish range", "category": "Garnish Sticks", "image": "/static/assets/ricevibe/garnish-2.jpg"},
    ],
    "media": [
        {"title": "Smaart Eats LLP unveils three brands that uphold sustainability", "source": "BW Hotelier", "date": "2021", "excerpt": "Smaart Eats unveiled three brands under its portfolio and strengthened its sustainable food and beverage vision.", "image": "/static/assets/media/4-600x600.png", "fit": "contain"},
        {"title": "Smaart Eats LLP launched amidst glitz, glamour and all things sustainable!", "source": "Business News This Week", "date": "2021", "excerpt": "A look at the launch of Smaart Eats and its growing portfolio of sustainable beverage and hospitality products.", "image": "/static/assets/media/2-600x600.png", "fit": "contain"},
        {"title": "A greener lifestyle - how our straws encourage conscious consumption habits", "source": "Passionate in Marketing", "date": "May 7, 2024", "excerpt": "Natural rice straws help reduce reliance on non-renewable resources and plastic waste.", "image": "/static/assets/media/7-1-724x1024.png", "fit": "contain"},
        {"title": "Rice Straws: A Small Switch for a Healthier You", "source": "Hans India", "date": "March 27, 2025", "excerpt": "Rice straws offer a small but meaningful switch toward healthier, more sustainable daily choices.", "image": "/static/assets/media/9-600x600.png", "fit": "contain"},
        {"title": "Top Sustainability Packaging Companies in India", "source": "Renewable India", "date": "2024", "excerpt": "Exploring eco-friendly innovation and sustainable packaging leaders in India.", "image": "/static/assets/media/1-1-724x1024.png", "fit": "contain"},
        {"title": "What is this straw made from rice?", "source": "Social media feature", "date": "April 4, 2025", "excerpt": "A visual product story introducing colourful rice straws and their natural material story.", "image": "/static/assets/media/10-1-724x1024.png", "fit": "contain"},
        {"title": "Sustainability on the Menu: How Restaurants are Embracing Rice Straws", "source": "The Balcony Stories", "date": "March 22, 2024", "excerpt": "Restaurants are embracing rice straws as a practical step toward sustainable service.", "image": "/static/assets/media/3-1-724x1024.png", "fit": "contain"},
        {"title": "Vishal Laddha Co-founder and CEO of Smaart Rice Straw", "source": "UP18 News", "date": "April 29, 2024", "excerpt": "A profile of Smaart Rice Straw and its sustainability-led beverage industry journey.", "image": "/static/assets/media/4-1-724x1024.png", "fit": "contain"},
        {"title": "Smaart Rice Straw: Revolutionizing Sustainability in the Beverage Industry", "source": "Satta Express", "date": "April 29, 2024", "excerpt": "A closer look at natural rice straws as an alternative to traditional plastic straws.", "image": "/static/assets/media/5-1-724x1024.png", "fit": "contain"},
        {"title": "A Greener Lifestyle", "source": "Sustainability press", "date": "2024", "excerpt": "Conscious consumption habits supported by practical eco-friendly beverage choices.", "image": "/static/assets/media/6-1-724x1024.png", "fit": "contain"},
        {"title": "Digital Footprint and Sustainable Choices", "source": "Live Smart Journal", "date": "2024", "excerpt": "A sustainability feature connecting everyday choices with a cleaner future.", "image": "/static/assets/media/8-1-724x1024.png", "fit": "contain"},
        {"title": "Smaart Eats Sustainability Feature", "source": "Press coverage", "date": "2024", "excerpt": "Smaart Eats and its sustainable product portfolio in the press.", "image": "/static/assets/media/7-600x600.png", "fit": "contain"},
        {"title": "Rice Straws Sustainability Coverage", "source": "Media feature", "date": "2024", "excerpt": "Rice straws, natural materials and the move away from plastic.", "image": "/static/assets/media/9-600x600.png", "fit": "contain"},
    ],
    "testimonials": [
        {"quote": "The rice straws give our beverage service a premium, natural finish and our guests notice the difference.", "name": "Cafe & Hospitality Partner", "role": "Chennai"},
        {"quote": "Ricevibe made it easy for us to move away from plastic without changing the way our team serves drinks.", "name": "Restaurant Operations Team", "role": "Tamil Nadu"},
        {"quote": "Reliable communication, thoughtful packaging and a product that fits our sustainability goals.", "name": "Eco-conscious Retailer", "role": "South India"},
    ],
    "videos": [
        {"title": "Ricevibe product overview", "url": "https://www.youtube.com/embed/ScMzIvxBSi4?si=9m1U8gG0uLQ6fAaH", "thumb": "/static/assets/media-3.svg"},
        {"title": "Event hospitality styling", "url": "https://www.youtube.com/embed/aqz-KE-bpKQ?si=9m1U8gG0uLQ6fAaH", "thumb": "/static/assets/gallery-2.svg"},
    ],
    "certificates": [
        {
            "name": "JP Enterprises Certificate of Business Registration",
            "issuer": "JP Enterprises",
            "validity": "Ongoing",
            "thumb": "/static/assets/cert-1.svg",
            "file": "/static/assets/cert-1.svg",
        },
        {
            "name": "Ricevibe Compliance Overview",
            "issuer": "Ricevibe Quality Team",
            "validity": "Annual review",
            "thumb": "/static/assets/cert-2.svg",
            "file": "/static/assets/cert-2.svg",
        },
    ],
    "faq": [
        {"question": "What are Ricevibe rice straws made from?", "answer": "Rice flour and tapioca starch."},
        {"question": "Do they change drink taste?", "answer": "No, they are taste-neutral."},
        {"question": "Are they suitable for hospitality use?", "answer": "Yes, they are designed for cafés, restaurants and event service. Confirm with Ricevibe for your exact application and packaging needs."},
        {"question": "Can I order for bulk wholesale?", "answer": "Yes, Ricevibe supports retail and bulk enquiries. Confirm with Ricevibe for MOQ and regional pricing."},
        {"question": "How should the products be stored?", "answer": "Keep in a cool, dry place away from moisture. Confirm with Ricevibe for specific storage guidance for your product line."},
    ],
    "policies": {
        "privacy": "We respect customer privacy and use enquiry details only for business communication and service support.",
        "terms": "All product information is indicative and subject to stock availability. Ricevibe reserves the right to revise product and pricing details.",
        "shipping": "Orders are fulfilled from Chennai, India. Delivery timelines vary based on order size, location and quantity. Confirm with Ricevibe for exact shipping schedules.",
        "returns": "Please contact Ricevibe immediately for damaged, missing or incorrect shipments. Confirm with Ricevibe for return eligibility on bulk and custom orders.",
    },
    "social": {
        "instagram": "https://www.instagram.com/",
        "facebook": "https://www.facebook.com/",
        "whatsapp": "https://wa.me/919342328664",
    },
    "contact_form_types": [
        "Retail",
        "Bulk",
        "Hotel/Cafe",
        "Distributor",
        "Media",
        "General",
    ],
}
