@extends('layouts.app')
@section('content')
<section class="page-hero compact"><div class="container"><span class="eyebrow">Contact</span><h1>Let’s talk supply, retail or hospitality enquiries</h1></div></section>
<section class="section"><div class="container contact-grid"><div class="contact-card"><h2>Get in touch</h2><p><strong>Phone:</strong> <a href="tel:+919342328664">{{ $site['brand']['phone'] }}</a></p><p><strong>Email:</strong> <a href="mailto:{{ $site['brand']['email'] }}">{{ $site['brand']['email'] }}</a></p><p><strong>Address:</strong> {{ $site['brand']['address'] }}</p><div class="qr-contact"><h3>Scan to connect</h3><div class="qr-connect"><figure><a href="{{ $site['social']['instagram'] }}"><img src="/static/assets/unnamed%20(1).jpg" alt="Ricevibe Instagram QR code" /></a><figcaption>Instagram</figcaption></figure><figure><a href="{{ $site['social']['whatsapp'] }}"><img src="/static/assets/unnamed.jpg" alt="Ricevibe WhatsApp QR code" /></a><figcaption>WhatsApp</figcaption></figure></div></div></div>
<form class="contact-form" method="post" action="{{ route('contact.submit') }}">@csrf @if(session('status'))<p class="form-status">{{ session('status') }}</p>@endif @if($errors->any())<p class="form-status">Please review the highlighted fields.</p>@endif
<div class="two-field-grid"><label><span>Name</span><input name="name" value="{{ old('name') }}" required />@error('name')<small>{{ $message }}</small>@enderror</label><label><span>Phone</span><input type="tel" name="phone" value="{{ old('phone') }}" required />@error('phone')<small>{{ $message }}</small>@enderror</label></div>
<div class="two-field-grid"><label><span>Email</span><input type="email" name="email" value="{{ old('email') }}" required />@error('email')<small>{{ $message }}</small>@enderror</label><label><span>Company</span><input name="company" value="{{ old('company') }}" /></label></div>
<label><span>Enquiry type</span><select name="enquiry_type">@foreach($site['contact_form_types'] ?? ['General'] as $type)<option value="{{ $type }}" @selected(old('enquiry_type') === $type)>{{ $type }}</option>@endforeach</select></label>
<label><span>Product</span><input name="product" value="{{ old('product', request('product')) }}" /></label><label><span>Message</span><textarea name="message" rows="5" required>{{ old('message') }}</textarea>@error('message')<small>{{ $message }}</small>@enderror</label><button class="btn primary" type="submit">Send enquiry</button></form></div></section>
@endsection